FROM eclipse-temurin:21-jre-jammy

RUN apt-get update && \
    apt-get install -y curl fontconfig && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://downloads.metabase.com/latest/metabase.jar -o /metabase.jar

CMD ["java", "-jar", "/metabase.jar"]