[project]
name = "e-commerce-clickstream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow==2.9.0",
    "apache-flink==2.2.0",
    "dbt-duckdb>=1.10.1",
    "faker>=40.11.1",
    "jupyter>=1.1.1",
    "kafka-python>=2.3.0",
    "notebook>=7.5.5",
    "pandas<3.0.0",
    "psycopg2-binary>=2.9.11",
    "pyarrow<21.0.0",
    "pytest>=9.0.3",
    "ruff>=0.15.13",
    "sqlfluff>=4.2.1",
    "sqlfluff-templater-dbt>=4.2.1",
]
