ecommerce_dbt:
  target: dev
  outputs:
    
    dev:
      type: duckdb
      path: 'ecommerce_data.duckdb'
      threads: 4
      connect_retries: 5
      extensions:
        - httpfs
        - aws
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

    prod:
      type: duckdb
      path: '/opt/airflow/ecommerce_dbt/ecommerce_data.duckdb'
      threads: 4
      connect_retries: 5
      extensions:
        - httpfs
        - aws
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"